# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ceab08d1630787be7b6b6282180f032cee8595bd37b8f29be23e3a5f6b2587c929b21159c39eb94e2dfa8e5f4363ffb329b34f2d06e72a4d431a8913ac88887

test:
  secret_key_base: f8ca1829533d0eaa33e4540b56ef39bf22834531317a158c3291367389e2a11a595d1e0d35e5106da9d16f54e430b7f11b3c5828726f177e6a3fc5a4c68b5367

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
